version: '3'

services:
  web:
    build: .
    command: bash -c "cd /app/code && python3 manage.py runserver 0.0.0.0:8000"
    links:
      - db:db
    volumes:
      - ./code:/app/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - DJANGO_LOG_LEVEL=DEBUG
  db:
    image: postgres:9.6
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54322:5432"

volumes:
  pgdata:
